
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pirappp
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:                            # Correct indentation for nodeSelector
        eks.amazonaws.com/nodegroup: stage    # Specify the node group name
      containers:
      - name: api
        image: sathish8329/uatbackend:91
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-api-service
  namespace: pirappp
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/src/app/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Should match the capacity specified in the PV
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
  namespace: pirappp
spec:
  containers:
  - name: pvc-access-container
    image: ubuntu
    command: ["/bin/sh", "-c", "tail -f /dev/null"]  # Keep the container running
    volumeMounts:
    - name: pvc-volume
      mountPath: /mnt/data  # Mount path within the container
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: api-logs-pvc  # Name of your PVC
