apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: pirappp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      nodeSelector:                    # Add this section for node selector
        eks.amazonaws.com/nodegroup: stage   # Specify the node group nam    
      containers:
      - name: auth
        image: sathish8329/uatauth:42
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-auth-service
  namespace: pirappp
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
