apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: pirappp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: sathish8329/uatauth:16
        ports:
        - containerPort: 8080
          httpGet:
            path: /api
            port: 443   # HTTPS port
            scheme: HTTPS
            host: stage.pripapp.io
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-auth-service
  namespace: pirappp
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
