apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pirapp-ingress
  namespace: pirapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "stage1.pirapp.io"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pirapp-api-service
            port:
              number: 8000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: pirapp-auth-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pirapp-frontend-service
            port:
              number: 80
