
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pirappp
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:                            # Correct indentation for nodeSelector
        eks.amazonaws.com/nodegroup: stage    # Specify the node group name
      containers:
      - name: api
        image: sathish8329/uatbackend:91
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-api-service
  namespace: pirappp
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-logs-pvs
  namespace: pirappp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/src/app/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bound-api-logs-pvc
  namespace: pirappp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: api-logs-pvs  # Specify the name of the PersistentVolume to bind to
