apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pirappp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sathish8329/uatbackend:39
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api   # Change this path based on your application's health check endpoint
            port: 8000   # Port where your application is listening
          initialDelaySeconds:  300 # Delay before first probe
          periodSeconds: 10         # How often to perform the probe
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-api-service
  namespace: pirappp
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
