apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pirapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        zone: ap-south-1b  # Adding the zone label here
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: new-kovaionai-ng
      containers:
      - name: frontend
        image: sathish8329/uatfront:46
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-frontend-service
  namespace: pirapp
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  # Adding the zone label to the service metadata
  labels:
    zone: ap-south-1b
