apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pirappp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Set maxUnavailable to 0 to avoid unavailability during update
      maxSurge: 1  # Set maxSurge to 1 to allow one additional pod during update  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sathish8329/uatfront:57
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-frontend-service
  namespace: pirappp
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
