apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pirappp
  # Adding the zone label to the deployment metadata
  labels:
    zone: ap-south-1a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sathish8329/uatbackend:10
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-api-service
  namespace: pirappp
  # Adding the zone label to the service metadata
  labels:
    zone: ap-south-1a
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
