apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: pirappp
  # Adding the zone label to the deployment metadata
  labels:
    zone: ap-south-1a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        zone: ap-south-1a  # Adding the zone label to the pod template
    spec:
      containers:
      - name: auth
        image: sathish8329/uatauth:11
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pirapp-auth-service
  namespace: pirappp
  # Adding the zone label to the service metadata
  labels:
    zone: ap-south-1a
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
